<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $pageTitle }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.5;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 20px;
            margin-bottom: 5px;
        }
        .header p {
            color: #666;
            margin: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $pageTitle }}</h1>
        <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>User</th>
                <th>Login at</th>
                <th>IP</th>
                <th>Location</th>
                <th>Browser | OS</th>
            </tr>
        </thead>
        <tbody>
            @forelse($loginLogs as $log)
                <tr>
                    <td>
                        {{ @$log->user->fullname ?? '-' }}<br>
                        <small>{{ @$log->user->username ?? '-' }}</small>
                    </td>
                    <td>{{ showDateTime($log->created_at) }}</td>
                    <td>{{ $log->user_ip }}</td>
                    <td>{{ __($log->city) }}<br>{{ __($log->country) }}</td>
                    <td>{{ __($log->browser) }}<br>{{ __($log->os) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="text-center">No login history found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ config('app.name') }}
    </div>
</body>
</html> 