<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $pageTitle }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.5;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 20px;
            margin-bottom: 5px;
        }
        .header p {
            color: #666;
            margin: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $pageTitle }}</h1>
        <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>User</th>
                <th>TRX</th>
                <th>Transacted</th>
                <th>Amount</th>
                <th>Post Balance</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            @forelse($transactions as $trx)
                <tr>
                    <td>
                        {{ $trx->user->fullname ?? '-' }}<br>
                        <small>{{ $trx->user->username ?? '-' }}</small>
                    </td>
                    <td>{{ $trx->trx }}</td>
                    <td>{{ showDateTime($trx->created_at) }}</td>
                    <td>
                        <span style="font-weight:bold; color:{{ $trx->trx_type == '+' ? '#1aa93f' : '#dc3545' }};">
                            {{ $trx->trx_type }} {{ showAmount($trx->amount) }}
                        </span>
                    </td>
                    <td>{{ showAmount($trx->post_balance) }}</td>
                    <td>{{ __($trx->details) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="text-center">No transactions found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ config('app.name') }}
    </div>
</body>
</html> 