<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Users Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.5;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 24px;
            margin-bottom: 5px;
        }
        .header p {
            color: #666;
            margin: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Users Report</h1>
        <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>User</th>
                <th>Email/Mobile</th>
                <th>Country</th>
                <th>Joined At</th>
                <th>Balance</th>
            </tr>
        </thead>
        <tbody>
            @forelse($users as $user)
                <tr>
                    <td>
                        {{ $user->fullname }}
                        <br>
                        <small>{{ $user->username }}</small>
                    </td>
                    <td>
                        {{ $user->email }}
                        <br>
                        {{ $user->mobileNumber }}
                    </td>
                    <td>{{ $user->country_code }}</td>
                    <td>
                        {{ showDateTime($user->created_at) }}
                        <br>
                        {{ diffForHumans($user->created_at) }}
                    </td>
                    <td>{{ showAmount($user->balance) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="text-center">No users found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ config('app.name') }}
    </div>
</body>
</html> 